POST http://localhost:8080/restaurants/
Content-Type: application/json

{
  "name": "sushidama",
  "address": "mokdong"
}

###

POST http://localhost:8080/restaurants/
Content-Type: application/json

{
  "name": "manimals",
  "address": "itaewon"
}

###

GET http://localhost:8080/restaurants

###