POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "poppo",
  "email": "poppo@gmail.com",
  "password": "password"
}

###

GET http://localhost:8080/users

###

POST http://localhost:8080/session
Content-Type: application/json

{
  "email": "poppo@gmail.com",
  "password": "password"
}

###