POST http://localhost:8080/restaurants/1/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjMzLCJ1c2VyTmFtZSI6InBvcHBvIn0.urySBGTtV3UuR45LysoDkvRoX0cASX6dE3a1KLBj0DM
Content-Type: application/json

{
  "description": "JMT",
  "score": 3
}

###

POST http://localhost:8080/restaurants/1/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjMzLCJ1c2VyTmFtZSI6InBvcHBvIn0.urySBGTtV3UuR45LysoDkvRoX0cASX6dE3a1KLBj0DM
Content-Type: application/json

{
  "description": "JMTGR",
  "score": 5
}

###